// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../smtc.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_update_display`, `_update_timeline`, `init_controls`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WindowsSmtc>>
abstract class WindowsSmtc implements RustOpaqueInterface {
  Future<void> close();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WindowsSmtc> newInstance() =>
      RustLib.instance.api.crateApiSmtcWindowsImplWindowsSmtcNew();

  Stream<SMTCControlEvent> subscribeToControlEvents();

  Future<void> updateDisplay({
    required String title,
    required String artist,
    String? imagePath,
    Uint8List? imageData,
  });

  Future<void> updateState({required SMTCState state});

  Future<void> updateTimeline({
    required PlatformInt64 position,
    required PlatformInt64 duration,
  });
}
